# Terminal Emulator Settings
window:
  padding:
    x: 20
    y: 20
  scrolling:
    history: 15
  opacity: 0.68

# Setting zsh as the default shell
shell:
    program: /bin/zsh

# Font
font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Medium

  bold:
    family: JetBrainsMono Nerd Font
    style: Bold

  italic:
    family: JetBrainsMono Nerd Font
    style: Italic

  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic

  size: 14

import:
  - ~/.config/alacritty/catppuccin.yml
