#! /bin/sh

#Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
killall picom; picom --experimental-backends &
killall dunst; dunst &
killall ksuperkey; ksuperkey -e 'Super_L=Alt_L|F1' &
feh --bg-fill -r -z ~/Pictures/Wallpapers &
redshift -x && redshift -O 4000k &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

#Workspaces
bspc monitor -d 1 2 3 4 5 6

#Others
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true

# workspace 1 (Terminals)
for i in kitty Alacritty Xfce4-terminal; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
for i in Firefox persepolis discord; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
for i in Thunar Pcmanfm qBittorrent; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
for i in Code VSCodium Geany "Code - OSS"; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
for i in vlc obs mpv mplayer lxmusic Gimp "Gimp-2.10" \
	"VirtualBox Manager"; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

#floating windows
for i in Alafloat Lxappearance Arandr sxiv mpv \
Viewnior mplayer2 feh Nm-connection-editor Matplotlib Yad; do
    bspc rule -a $i state=floating follow=on focus=on; done
