#! /bin/sh

# Set Correct Scaling
xrandr --output HDMI-0 --scale 0.5

#Autostart
killall sxhkd; sxhkd &
killall picom; picom &
killall dunst; dunst &
feh --bg-fill -r -z ~/Pictures/Wallpapers &
redshift -x && redshift -O 4000k &
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &

#variable
alias bc='bspc config'
alias br='bspc rule'

#Workspaces
bspc monitor -d 1 2 3 4 5 6

#Others
bc border_width 0
bc window_gap 6
bc split_ratio 0.50
bc borderless_monocle true
bc gapless_monocle false
bc focus_follows_pointer true

# workspace 1 (Terminals)
declare -a terminal=(kitty Alacritty Xfce4-terminal)
for i in ${terminal[@]}; do
    bspc rule -a $i desktop='^1' follow=on focus=on; done

# workspace 2 (Internet Browser)
declare -a web=(firefox discord)
for i in ${web[@]}; do
    bspc rule -a $i desktop='^2' follow=on focus=on; done

# workspace 3 (Files)
declare -a filem=(Thunar Pcmanfm qBittorrent)
for i in ${filem[@]}; do
    bspc rule -a $i desktop='^3' follow=on focus=on; done

# workspace 4 (Text Editor)
declare -a office=(Code VSCodium Geany)
for i in ${office[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 5 (Media)
declare -a media=(vlc obs mpv mplayer lxmusic Gimp Gimp-2.10 \
"VirtualBox Manager")
for i in ${media[@]}; do
    bspc rule -a $i desktop='^5' follow=on focus=on; done

# floating windows
declare -a floats=(Alafloat Lxappearance Arandr sxiv mpv \
Viewnior mplayer2 Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done
